//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PremiumWebServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string tokenid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string corpname { get; set; }
        public string phone { get; set; }
        public string localphone { get; set; }
        public string direction { get; set; }
        public string email { get; set; }
        public string pubkey { get; set; }
        public string subkey { get; set; }
    }
}
